import assert from 'node:assert/strict';
import { parseCommand as P, suggest } from '../js/commands.js';
const near = (a, b, t = 1e-9) => assert.ok(Math.abs(a - b) <= t * Math.max(1, Math.abs(b)), `${a} != ${b}`);
const d = (p, q) => Math.hypot(p.x - q.x, p.y - q.y);
const sides = (pts) => pts.map((p, i) => d(p, pts[(i + 1) % pts.length]));
let r = P('triangle 3 4 5'); assert.equal(r.do, 'shape'); assert.deepEqual(sides(r.pts).map((x) => +x.toFixed(9)), [3, 4, 5]);
assert.throws(() => P('triangle 1 1 5'), /No triangle/);
r = P('triangle sas 5 60 4'); near(d(r.pts[0], r.pts[2]), 5); near(d(r.pts[0], r.pts[1]), 4);
r = P('triangle asa 50 6 70'); near(d(r.pts[0], r.pts[1]), 6);
r = P('right triangle 3 4'); near(sides(r.pts)[1], 5);
r = P('equilateral sqrt(3)'); sides(r.pts).forEach((s) => near(s, Math.sqrt(3)));
r = P('regular 7 side 3'); assert.equal(r.pts.length, 7); sides(r.pts).forEach((s) => near(s, 3));
r = P('hexagon r 2'); sides(r.pts).forEach((s) => near(s, 2));
r = P('8-gon 1'); assert.equal(r.pts.length, 8);
r = P('circle r=2 at (1,1)'); assert.deepEqual([r.kind, r.rx, r.at], ['ellipse', 2, { x: 1, y: 1 }]);
r = P('circle (1, -1) 3'); assert.deepEqual([r.rx, r.at], [3, { x: 1, y: -1 }]);
r = P('circle d=4'); assert.equal(r.rx, 2);
r = P('rectangle 4x2'); near(sides(r.pts)[0], 4); near(sides(r.pts)[1], 2);
r = P('square 3 rotated 45'); assert.equal(r.rot, 45);
r = P('line (0,0) (4,3)'); assert.deepEqual([r.do, r.ext, r.b], ['line', 'segment', { x: 4, y: 3 }]);
r = P('infinite line (0,0) (1,2)'); assert.equal(r.ext, 'line');
r = P('point A (2, 3)'); assert.deepEqual([r.do, r.label, r.p], ['point', 'A', { x: 2, y: 3 }]);
r = P('B = (1, sqrt(2))'); assert.equal(r.label, 'B'); near(r.p.y, Math.SQRT2);
r = P('(1,2)'); assert.equal(r.do, 'point');
r = P('polygon (0,0) (4,0) (3,3) (0,2)'); assert.equal(r.pts.length, 4);
r = P('y = x^2 - 3'); assert.deepEqual(r, { do: 'func', expr: 'x^2 - 3' });
r = P('a = pi/2'); assert.equal(r.do, 'slider'); near(r.value, Math.PI / 2);
r = P('slider b 0 10'); assert.deepEqual([r.name, r.min, r.max], ['b', 0, 10]);
r = P('grid 0.5'); assert.deepEqual([r.name, r.arg], ['gridSize', 0.5]);
r = P('exact off'); assert.equal(r.arg, false);
r = P('text Hello world at (0,4)'); assert.deepEqual([r.text, r.at], ['Hello world', { x: 0, y: 4 }]);
r = P('angle (3,0) (0,0) (0,3)'); assert.equal(r.do, 'angle');
r = P('ellipse 3 2'); assert.deepEqual([r.rx, r.ry], [3, 2]);
assert.throws(() => P('banana 3'), /don’t know/);
assert.ok(suggest('tri').length > 0 && suggest('tri')[0][0].startsWith('tri'));
console.log('✓ commands');
